
table:
        gcc -w -c -g table.c
        gcc -w -c -g menu.c
        gcc -w -c -g main.c
        ar cr libtable.a table.o
        gcc -w main.o menu.o table.o -o a.out -L. -ltable
        valgrind ./a.out
clean:
        rm *.o
        rm *.a
        rm a.out
